apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-prompt-shell-cm
  namespace: shenma
data:
  config.yaml: |
    ENV: __env_profile
    APP_NAME: "ai-prompt-shell"
    LOGGER:
      LEVEL: "debug"
      FORMAT: "text"
      OUTPUT: "stdout"
      FILE_NAME: "ai-prompt-shell.log"

    SERVER:
      LISTEN_ADDR: ":8080"
      DEBUG: true

    REDIS:
      ADDR: "${{__env_profile.redis.addr}}"
      PASSWORD: ""
      DB: 0

    REFRESH:
      TOOL: "5m"
      EXTENSION: "5m"
      PROMPT: "5m"
      ENVIRON: "5m"

    LLM:
      API_KEY: ""
      API_BASE: "${{__env_profile.llm.addr}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-prompt-shell
  namespace: shenma
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ai-prompt-shell
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ai-prompt-shell
    spec:
      containers:
      - image: ${{SHENMA_DOCKER_REPO}}/ai-prompt-shell:${{IMAGE_TIMESTAMP}}
        imagePullPolicy: Always
        name: ai-prompt-shell
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /config.yaml
            name: config-volume
            subPath: config.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: ai-prompt-shell-cm
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ai-prompt-shell
      serviceAccountName: ai-prompt-shell
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  namespace: shenma
  name: ai-prompt-shell
  labels:
    app: ai-prompt-shell
spec:
  # pod的标签选择器
  type: NodePort
  selector:
    app: ai-prompt-shell
  # 暴露的端口列表
  ports:
    # HTTP服务端口
    - name: http
      port: 80
      nodePort: 31225
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: shenma
  name: ai-prompt-shell


