basePath: /
definitions:
  api.ChatModelRequest:
    properties:
      model:
        type: string
      args:
        additionalProperties: true
        type: object
    type: object
  dao.Contributes:
    properties:
      dependences:
        items:
          $ref: '#/definitions/dao.Dependence'
        type: array
      languages:
        items:
          type: string
        type: array
      prompts:
        items:
          $ref: '#/definitions/dao.Prompt'
        type: array
    type: object
  dao.Dependence:
    properties:
      failStrategy:
        type: string
      name:
        type: string
      version:
        type: string
    type: object
  dao.Engines:
    properties:
      name:
        type: string
      version:
        type: string
    type: object
  dao.Grpc:
    properties:
      method:
        type: string
      url:
        type: string
    type: object
  dao.Message:
    properties:
      content:
        type: string
      role:
        type: string
    type: object
  dao.Prompt:
    properties:
      description:
        type: string
      messages:
        items:
          $ref: '#/definitions/dao.Message'
        type: array
      name:
        type: string
      parameters:
        additionalProperties: true
        type: object
      prompt:
        type: string
      returns:
        additionalProperties: true
        type: object
      supports:
        items:
          type: string
        type: array
    type: object
  dao.PromptExtension:
    properties:
      contributes:
        $ref: '#/definitions/dao.Contributes'
      description:
        type: string
      displayName:
        type: string
      engines:
        $ref: '#/definitions/dao.Engines'
      extensionType:
        type: string
      icon:
        type: string
      license:
        type: string
      name:
        type: string
      publisher:
        type: string
      version:
        type: string
    type: object
  dao.Restful:
    properties:
      method:
        type: string
      url:
        type: string
    type: object
  dao.Tool:
    properties:
      description:
        type: string
      examples:
        items:
          type: string
        type: array
      grpc:
        $ref: '#/definitions/dao.Grpc'
      module:
        type: string
      name:
        type: string
      parameters:
        additionalProperties: true
        type: object
      restful:
        $ref: '#/definitions/dao.Restful'
      returns:
        additionalProperties: true
        type: object
      supports:
        items:
          type: string
        type: array
      type:
        type: string
    type: object
  service.ChatResponse:
    properties:
      choices:
        items:
          properties:
            finish_reason:
              type: string
            index:
              type: integer
            logprobs:
              type: object
            message:
              properties:
                content:
                  type: string
                role:
                  type: string
              type: object
          type: object
        type: array
      created:
        type: integer
      id:
        type: string
      model:
        type: string
      object:
        type: string
      usage:
        properties:
          completion_tokens:
            type: integer
          prompt_tokens:
            type: integer
          total_tokens:
            type: integer
        type: object
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for AI Prompt Shell
  title: AI Prompt Shell API
  version: "1.0"
paths:
  /api/environs:
    get:
      description: Get all defined environment variables in system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: List all environment variables
      tags:
      - Environs
  /api/environs/{environ_id}:
    get:
      description: Get value of specified environment variable
      parameters:
      - description: Environment variable ID
        in: path
        name: environ_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "404":
          description: Not Found
          schema: {}
      summary: Get environment variable
      tags:
      - Environs
  /api/extensions:
    get:
      description: Get all available prompt extension IDs in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: List all prompt extension IDs
      tags:
      - Extensions
  /api/extensions/{extension_id}:
    get:
      description: Get detailed information of prompt extension by ID
      parameters:
      - description: Extension ID
        in: path
        name: extension_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dao.PromptExtension'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get specified prompt extension details
      tags:
      - Extensions
  /api/prompts:
    get:
      description: Get all available prompt templates in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: List all prompt templates
      tags:
      - Prompts
  /api/prompts/{prompt_id}:
    get:
      description: Get detailed information of prompt template by ID
      parameters:
      - description: Prompt template ID
        in: path
        name: prompt_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dao.Prompt'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get specified prompt template details
      tags:
      - Prompts
  /api/prompts/{prompt_id}/chat:
    post:
      consumes:
      - application/json
      description: Chat interaction with LLM using specified prompt template
      parameters:
      - description: Prompt template ID
        in: path
        name: prompt_id
        required: true
        type: string
      - description: Chat parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.ChatModelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ChatResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Interact with LLM using prompt
      tags:
      - Prompts
  /api/prompts/{prompt_id}/render:
    post:
      consumes:
      - application/json
      description: Render the prompt template with given args
      parameters:
      - description: Prompt template ID
        in: path
        name: prompt_id
        required: true
        type: string
      - description: Rendering parameters
        in: body
        name: request
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Render specified prompt template
      tags:
      - Prompts
  /api/tools:
    get:
      description: Get a list of all available tools in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: List all tools
      tags:
      - Tools
  /api/tools/{tool_id}:
    get:
      description: Get detailed information about specified tool
      parameters:
      - description: 工具ID
        in: path
        name: tool_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dao.Tool'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get tool details
      tags:
      - Tools
swagger: "2.0"
